version: '3.8'
services:
  app:
    image: ekaii-web-app
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on: [db]
  db:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: ekaii
        MYSQL_USER: ekaii
        MYSQL_PASSWORD: ekaii
    ports:
      - "3306:3306"
