services:
  db:
    container_name: ekaii-db
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    environment:
        POSTGRES_PASSWORD: ekaii
        POSTGRES_USER: ekaii
        POSTGRES_DB: ekaii
    ports:
      - "5432:5432"
  app:
    container_name: ekaii-app
    build:
      context: ./
      target: prod
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on: [ db ]
    environment:
      - DATABASE_URL=postgres://ekaii:ekaii@ekaii-db:5432/ekaii
