import type { Metadata } from "next";
import "./globals.css";
import {monocraft, rubik} from "@/fonts/fonts";

export const metadata: Metadata = {
  title: "Ekaii",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={'h-full'}>
      <body className={`${rubik.className} ${monocraft.variable} min-h-full`}>
        {children}
      </body>
    </html>
  );
}
