import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'
import Header from "@/components/Header";

const inter = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ekaii',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
