name: Build App Docker Image
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get release version
        run: |
          VERSION=$(echo "${GITHUB_REF}" | sed -n 's/refs\/tags\/v//p')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build Docker Image
        run: docker build -t ghcr.io/ekaiimc/ekaii-web-app:${{ env.VERSION }} -t ghcr.io/ekaiimc/ekaii-web-app:latest --target prod -f ./docker/web/Dockerfile .
      - name: Push Docker Image
        run: |
          docker push ghcr.io/ekaiimc/ekaii-web-app:${{ env.VERSION }}
          docker push ghcr.io/ekaiimc/ekaii-web-app:latest
      - name: Deploy on Coolify
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'